use std::ops::Deref;

use crate::new_types::instrument::InstrId;
use bytemuck::{Pod, Zeroable};

use super::types::Discriminator;

#[cfg(feature = "on-chain")]
use solana_program::pubkey::Pubkey;

#[repr(C)]
#[derive(Pod, Zeroable, Clone, Copy, Default)]
pub struct InstrAccountHeader {
    pub discriminator: Discriminator,
    pub instr_id: InstrId,
    pub asset_token_id: u32,
    pub crncy_token_id: u32,
    pub mask: u32,
    pub maps_address: Pubkey,
    pub perp_maps_address: Pubkey,
    pub lut_address: Pubkey,
    pub feed_id: Pubkey,
    pub drv_count: u32,
    pub asset_token_decs_count: u32,
    pub crncy_token_decs_count: u32,
    pub slot: u32,
    pub creator: Pubkey,
    pub last_time: u32,
    pub distrib_time: u32,
    pub base_crncy_index: u32,
    pub instance_counter: u32,
    pub variance_counter: u32,
    pub bids_tree_nodes_count: u32,
    pub bids_tree_lines_entry: u32,
    pub bids_tree_orders_entry: u32,
    pub asks_tree_nodes_count: u32,
    pub asks_tree_lines_entry: u32,
    pub asks_tree_orders_entry: u32,
    pub bid_lines_begin: u32,
    pub bid_lines_end: u32,
    pub bid_lines_count: u32,
    pub ask_lines_begin: u32,
    pub ask_lines_end: u32,
    pub ask_lines_count: u32,
    pub bid_orders_count: u32,
    pub ask_orders_count: u32,
    pub fixing_time: u32,
    pub fixing_crncy_tokens: i64,
    pub fixing_asset_tokens: i64,
    pub counter: i64,
    pub asset_tokens: i64,
    pub crncy_tokens: i64,
    pub pool_fees: i64,
    pub ps: i64,
    pub protocol_fees: i64,
    pub hits_counter: i64,
    pub last_asset_tokens: i64,
    pub last_crncy_tokens: i64,
    pub perp_underlying_px: i64,
    pub last_px: i64,
    pub best_bid: i64,
    pub best_ask: i64,
    pub fixing_px: i64,
    pub variance: f64,
    pub avg_spread: f64,
    pub last_spread: f64,
    pub last_spread_time: u32,
    pub total_spread_period: u32,
    pub last_close: i64,
    pub day_asset_tokens: i64,
    pub day_crncy_tokens: i64,
    pub day_low: i64,
    pub day_high: i64,
    pub prev_day_asset_tokens: i64,
    pub prev_day_crncy_tokens: i64,
    pub alltime_asset_tokens: f64,
    pub alltime_crncy_tokens: f64,
    pub day_trades: u32,
    pub prev_day_trades: u32,
    pub lp_day_trades: u32,
    pub lp_prev_day_trades: u32,
    pub alltime_trades: i64,
    pub dec_factor: i64,
    pub perp_clients_count: u32,
    pub perp_slot: u32,
    pub perp_time: u32,
    pub perp_funding_rate_slot: u32,
    pub perp_funding_rate_time: u32,
    pub perp_long_px_tree_nodes_count: u32,
    pub perp_long_px_tree_entry: u32,
    pub perp_short_px_tree_nodes_count: u32,
    pub perp_short_px_tree_entry: u32,
    pub perp_rebalance_time_tree_nodes_count: u32,
    pub perp_rebalance_time_tree_entry: u32,
    pub perp_bids_tree_nodes_count: u32,
    pub perp_bids_tree_lines_entry: u32,
    pub perp_bids_tree_orders_entry: u32,
    pub perp_asks_tree_nodes_count: u32,
    pub perp_asks_tree_lines_entry: u32,
    pub perp_asks_tree_orders_entry: u32,
    pub perp_bid_lines_begin: u32,
    pub perp_bid_lines_end: u32,
    pub perp_bid_lines_count: u32,
    pub perp_ask_lines_begin: u32,
    pub perp_ask_lines_end: u32,
    pub perp_ask_lines_count: u32,
    pub perp_bid_orders_count: u32,
    pub perp_ask_orders_count: u32,
    pub perp_day_trades: u32,
    pub perp_prev_day_trades: u32,
    pub creation_time: u32,
    pub perp_alltime_trades: i64,
    pub perp_spot_price_for_withdrowal: i64,
    pub perp_soc_loss_long_rate: f64,
    pub perp_soc_loss_short_rate: f64,
    pub perp_open_int: i64,
    pub perp_price_delta: f64,
    pub perp_funding_rate: f64,
    pub perp_funding_funds: i64,
    pub perp_soc_loss_funds: i64,
    pub perp_insurance_fund: i64,
    pub perp_last_close: i64,
    pub perp_last_asset_tokens: i64,
    pub perp_last_crncy_tokens: i64,
    pub perp_last_px: i64,
    pub perp_best_bid: i64,
    pub perp_best_ask: i64,
    pub perp_day_asset_tokens: i64,
    pub perp_day_crncy_tokens: i64,
    pub perp_day_low: i64,
    pub perp_day_high: i64,
    pub perp_prev_day_asset_tokens: i64,
    pub perp_prev_day_crncy_tokens: i64,
    pub perp_alltime_asset_tokens: f64,
    pub perp_alltime_crncy_tokens: f64,
    pub max_leverage: f64,
    pub day_volatility: f64,
    pub liquidation_threshold: f64,
    pub seats_reserve: i64,
    pub reserved_value1: i64,
    pub reserved_value2: i64,
    pub reserved_value3: i64,
    pub reserved_value4: i64,
    pub reserved_value5: i64,
    pub reserved_value6: i64,
    pub reserved_value7: i64,
    pub reserved_value8: i64,
    pub reserved_value9: i64,
    pub reserved_value10: i64,
}

impl Deref for InstrAccountHeader {
    type Target = Discriminator;

    fn deref(&self) -> &Self::Target {
        &self.discriminator
    }
}

pub const INSTR_ACCOUNT_HEADER_SIZE: usize = std::mem::size_of::<InstrAccountHeader>();
